settings:
  title: 'Status Page'
  url: 'https://status.projectmouseion.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:    
  - id: nzbget
    name: NZBGet
    description: '' # default=empty
    url: 'https://nzbget.projectmouseion.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: radarr
    name: Radarr
    description: '' # default=empty
    url: 'https://radarr.projectmouseion.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: sonarr
    name: Sonarr
    description: '' # default=empty
    url: 'https://sonarr.projectmouseion.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: bazarr
    name: Bazarr
    description: '' # default=empty
    url: 'https://bazarr.projectmouseion.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: projectmouseion
    name: 'Project Mouseion'
    description: '' # default=empty
    url: 'https://projectmouseion.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
  
  - id: mega
    name: 'Mega.nz'
    description: '' # default=empty
    url: 'https://mega.nz' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
  
  - id: plex
    name: Plex
    description: '' # default=empty
    url: 'https://plex.tv' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: jackdallas-me # unique identifier
    name: jackdallas.me
    description: 'Homepage.' # default=empty
    url: 'https://jackdallas.me/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
