name = "cf-workers-status-page"
workers_dev = false
account_id = "fa4fbe6b023e6886d26ab6bb3b53cc95"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
##zone_id="f6474b30b347bc45178cc13c4bfd1830"
#route="status.dallasthe.dev/*"
